/* =====================================================================
   MODEL — the data and state of the app. Never touches the DOM.
   Edit your content here: the Biblioteca document groups, Top Anime list.
   ===================================================================== */

const Model = {

  // Where the contact form delivers (via formsubmit.co relay)
  contactEmail: "esegueldelafuente@gmail.com",

  // App state (read/written by the Controller, displayed by the View)
  state: {
    screen: "home",        // which screen is showing
    menuIndex: 0,          // selected item on the home menu
    libraryBuilt: false,
    animePage: 0,          // current page on the Top Anime screen
  },

  // ---- Biblioteca: legal document library, grouped by category ----
  // Groups render top to bottom in this order. Each item needs a `title`;
  // `desc` and `file` can stay empty while a document is still pending —
  // it then shows a "Próximamente" card instead of a link. Once a PDF is
  // ready, drop it in assets/documentos/ and point `file` at it.
  library: [
    {
      label: "Leyes",
      sortNumeric: true,
      items: [
        {
          title: "LEY N° 18.961",
          desc: "Ley N° 18.961, Ley Orgánica Constitucional de Carabineros de Chile.",
          file: "assets/documentos/ley-18961.pdf",
        },
      ],
    },
    {
      label: "Reglamentos",
      featured: true,
      items: [
        { title: "REGLAMENTO 11", desc: "Reglamento de disciplina de Carabineros de Chile Nº 11", file: "assets/documentos/reglamento-11.pdf" },
        { title: "REGLAMENTO 15", desc: "Reglamento de sumario administrativo de Carabineros de Chile Nº 15", file: "assets/documentos/reglamento-15.pdf" },
      ],
    },
    {
      label: "Órdenes generales",
      sortNumeric: true,
      items: [
        {
          title: "ORDEN GENERAL N° 2.554",
          desc: "Orden de fecha 05.03.2018 que modifica la Directiva Complementaria del Reglamento de Vehículos N° 20, sobre accidentes de tránsito con vehículos de Carabineros: define a qué autoridad remitir los sumarios según la región y cuándo procede la exoneración de responsabilidad por caso fortuito.",
          file: "assets/documentos/orden-general-2554.pdf",
        },
      ],
    },
    {
      label: "Circulares",
      sortNumeric: true,
      items: [
        {
          title: "CIRCULAR N° 1.849",
          desc: "Circular de fecha 29.05.2020 de la Dirección General de Carabineros, que imparte instrucciones sobre el proceso reglamentario para tramitar peticiones y/o reclamos del personal: obliga a las Jefaturas a dar respuesta oportuna, informada y fundamentada a sus subalternos a través del conducto regular, considerando falta a la disciplina el incumplimiento de esta obligación.",
          file: "assets/documentos/circular-1849.pdf",
        },
        {
          title: "CIRCULAR N° 1.905",
          desc: "Circular de fecha 24.12.2025 de la Dirección Nacional de Personal de Carabineros, que actualiza las instrucciones sobre el ejercicio de la potestad disciplinaria: cuándo procede sumario, investigación o explicaciones verbales, fijación y registro de domicilio, reglas de notificación, y los recursos, plazos y forma de presentación conforme a los Reglamentos N° 11 y N° 15.",
          file: "assets/documentos/circular-1905.pdf",
        },
      ],
    },
    {
      label: "Instrucciones",
      items: [
        {
          title: "Instructivo Dijuscar N° 1 (análisis artículo 86° Reglamento N° 15)",
          desc: "Instructivo de la Dirección de Justicia de Carabineros que analiza la jurisprudencia de la Contraloría General de la República sobre el artículo 86° del Reglamento de Sumarios N° 15, e instruye que la baja por conducta mala con efectos inmediatos y la resolución del sumario corresponden al mando directo del funcionario involucrado, no al mando territorial del lugar del hecho.",
          file: "assets/documentos/instructivo-dijuscar-1.pdf",
        },
      ],
    },
    {
      label: "Documentos varios",
      items: [
        {
          title: "Recopilación de materias administrativas más recurrentes, relacionadas con la tramitación de Reclamos",
          desc: "Documento de fecha 31.12.2024, elaborado por el Depto. Reclamos y Sugerencias de la Contraloría General de Carabineros.",
          file: "assets/documentos/recopilado-materias-reclamos.pdf",
        },
        {
          title: "Protocolo Grúas Particulares",
          desc: "Protocolo que regula el requerimiento de servicios de grúa particular para el retiro de vehículos desde la vía pública: prioriza el servicio del propio afectado o su seguro, exige empadronamiento y acreditación legal de las empresas de grúa cuando no lo hay, detalla el contenido mínimo del acta de recepción del vehículo, y prohíbe al personal de Carabineros recibir dineros, aportes o pactar acuerdos con empresas de grúas.",
          file: "assets/documentos/protocolo-gruas.pdf",
        },
      ],
    },
  ],

  // ---- Top Anime screen ----
  // Completed anime only, from the MyAnimeList export, sorted by score
  // descending (ties broken alphabetically). Paginated in the view —
  // see animePageSize.
  animePageSize: 20,
  animeList: [
    { title: "Air", score: 10 },
    { title: "Air in Summer", score: 10 },
    { title: "Bananya", score: 10 },
    { title: "Bananya: Fushigi na Nakama-tachi", score: 10 },
    { title: "Cardcaptor Sakura", score: 10 },
    { title: "Clannad", score: 10 },
    { title: "Clannad Movie", score: 10 },
    { title: "Clannad: After Story", score: 10 },
    { title: "Dungeon Meshi", score: 10 },
    { title: "Eyeshield 21", score: 10 },
    { title: "Fullmetal Alchemist: Brotherhood", score: 10 },
    { title: "Hunter x Hunter (2011)", score: 10 },
    { title: "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen", score: 10 },
    { title: "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen OVA", score: 10 },
    { title: "Kenpuu Denki Berserk", score: 10 },
    { title: "Log Horizon", score: 10 },
    { title: "Mahou Shoujo Lyrical Nanoha", score: 10 },
    { title: "Mahou Shoujo Lyrical Nanoha A's", score: 10 },
    { title: "Mahou Shoujo Lyrical Nanoha StrikerS", score: 10 },
    { title: "Mahou Shoujo Lyrical Nanoha: The Movie 1st", score: 10 },
    { title: "Monster", score: 10 },
    { title: "Project Sekai Movie: Kowareta Sekai to Utaenai Miku", score: 10 },
    { title: "Rozen Maiden", score: 10 },
    { title: "Sakamoto Days Part 2", score: 10 },
    { title: "Samurai Champloo", score: 10 },
    { title: "Shakugan no Shana", score: 10 },
    { title: "Shakugan no Shana II (Second)", score: 10 },
    { title: "Sousou no Frieren", score: 10 },
    { title: "Tiger & Bunny", score: 10 },
    { title: "Tiger & Bunny 2", score: 10 },
    { title: "Tiger & Bunny 2 Part 2", score: 10 },
    { title: "Tiger & Bunny Movie 2: The Rising", score: 10 },
    { title: "Wotaku ni Koi wa Muzukashii OVA", score: 10 },
    { title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru.", score: 10 },
    { title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan", score: 10 },
    { title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku", score: 10 },
    { title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA", score: 10 },
    { title: "Yuu☆Yuu☆Hakusho", score: 10 },
    { title: "Air Movie", score: 9 },
    { title: "Akira", score: 9 },
    { title: "Amaama to Inazuma", score: 9 },
    { title: "Amagi Brilliant Park", score: 9 },
    { title: "Amagi Brilliant Park: Wakuwaku Mini Theater - Rakugaki Backstage", score: 9 },
    { title: "Baccano!", score: 9 },
    { title: "Baki", score: 9 },
    { title: "Bakuman. 2nd Season", score: 9 },
    { title: "Bakuman. 3rd Season", score: 9 },
    { title: "Banana Fish", score: 9 },
    { title: "Cardcaptor Sakura Movie 2: Fuuin Sareta Card", score: 9 },
    { title: "Chrno Crusade", score: 9 },
    { title: "Clannad: After Story - Mou Hitotsu no Sekai, Kyou-hen", score: 9 },
    { title: "Cowboy Bebop", score: 9 },
    { title: "Dagashi Kashi", score: 9 },
    { title: "Dagashi Kashi 2", score: 9 },
    { title: "Dandadan", score: 9 },
    { title: "Darker than Black: Kuro no Keiyakusha", score: 9 },
    { title: "Darker than Black: Kuro no Keiyakusha Gaiden", score: 9 },
    { title: "Death Parade", score: 9 },
    { title: "Devil May Cry", score: 9 },
    { title: "Dorohedoro", score: 9 },
    { title: "Drifters", score: 9 },
    { title: "Durarara!!", score: 9 },
    { title: "Full Metal Panic? Fumoffu", score: 9 },
    { title: "Gantz", score: 9 },
    { title: "Gokushufudou", score: 9 },
    { title: "Gokushufudou Part 2", score: 9 },
    { title: "Gokushufudou Season 2", score: 9 },
    { title: "Great Teacher Onizuka", score: 9 },
    { title: "Gyakuten Saiban: Sono \"Shinjitsu\", Igi Ari!", score: 9 },
    { title: "Hajime no Ippo", score: 9 },
    { title: "Hajime no Ippo: New Challenger", score: 9 },
    { title: "Hajime no Ippo: Rising", score: 9 },
    { title: "Hataraku Saibou!!", score: 9 },
    { title: "Hunter x Hunter", score: 9 },
    { title: "Inazuma Eleven", score: 9 },
    { title: "InuYasha", score: 9 },
    { title: "InuYasha: Kanketsu-hen", score: 9 },
    { title: "Jigoku Sensei Nube", score: 9 },
    { title: "Jujutsu Kaisen", score: 9 },
    { title: "Jujutsu Kaisen 0 Movie", score: 9 },
    { title: "Jujutsu Kaisen 2nd Season", score: 9 },
    { title: "Kaginado", score: 9 },
    { title: "Kimi ni Todoke", score: 9 },
    { title: "Kimi ni Todoke 2nd Season", score: 9 },
    { title: "Log Horizon: Entaku Houkai", score: 9 },
    { title: "Love Hina", score: 9 },
    { title: "Love Hina Again", score: 9 },
    { title: "Lovely★Complex", score: 9 },
    { title: "Lucky☆Star", score: 9 },
    { title: "Majutsushi Orphen", score: 9 },
    { title: "Mousou Dairinin", score: 9 },
    { title: "Naruto", score: 9 },
    { title: "Paripi Koumei", score: 9 },
    { title: "Peach Girl", score: 9 },
    { title: "Pokemon Generations", score: 9 },
    { title: "Poputepipikku 2nd Season", score: 9 },
    { title: "Ranma ½", score: 9 },
    { title: "Shaman King", score: 9 },
    { title: "Shouwa Genroku Rakugo Shinjuu", score: 9 },
    { title: "Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen", score: 9 },
    { title: "Shouwa Genroku Rakugo Shinjuu: Yotarou Hourou-hen", score: 9 },
    { title: "Spy x Family Part 2", score: 9 },
    { title: "Spy x Family Season 2", score: 9 },
    { title: "Sumomomo Momomo: Chijou Saikyou no Yome", score: 9 },
    { title: "Suzumiya Haruhi no Yuuutsu", score: 9 },
    { title: "Tate no Yuusha no Nariagari", score: 9 },
    { title: "Tokyo Revengers", score: 9 },
    { title: "Undead Unluck", score: 9 },
    { title: "WWW.Working!!", score: 9 },
    { title: "Wagamama☆Fairy Mirumo de Pon!", score: 9 },
    { title: "Working!!", score: 9 },
    { title: "Working!!!", score: 9 },
    { title: "Working'!!", score: 9 },
    { title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan: Dakara, Shishunki wa Owarazu ni, Seishun wa Tsuzuiteiku.", score: 9 },
    { title: "Yuri!!! on Ice", score: 9 },
    { title: "Yu☆Gi☆Oh! 5D's", score: 9 },
    { title: "Yu☆Gi☆Oh! Duel Monsters", score: 9 },
    { title: "Yu☆Gi☆Oh! Duel Monsters GX", score: 9 },
    { title: "Accel World", score: 8 },
    { title: "Aggressive Retsuko (ONA) 2nd Season", score: 8 },
    { title: "Akatsuki no Yona", score: 8 },
    { title: "Akatsuki no Yona OVA", score: 8 },
    { title: "Atarashii Joushi wa Do Tennen", score: 8 },
    { title: "Bakuman.", score: 8 },
    { title: "Black Bullet", score: 8 },
    { title: "Bounen no Xamdou", score: 8 },
    { title: "Chainsaw Man", score: 8 },
    { title: "Chobits", score: 8 },
    { title: "Chuunibyou demo Koi ga Shitai!", score: 8 },
    { title: "Clannad: Mou Hitotsu no Sekai, Tomoyo-hen", score: 8 },
    { title: "Death Note", score: 8 },
    { title: "Digimon Tamers", score: 8 },
    { title: "Dimension W", score: 8 },
    { title: "Dr. Stone", score: 8 },
    { title: "Dragon Ball", score: 8 },
    { title: "Durarara!!x2 Ketsu", score: 8 },
    { title: "Durarara!!x2 Shou", score: 8 },
    { title: "Durarara!!x2 Ten", score: 8 },
    { title: "Elfen Lied", score: 8 },
    { title: "Ergo Proxy", score: 8 },
    { title: "Gangsta.", score: 8 },
    { title: "Genshiken", score: 8 },
    { title: "Gintama", score: 8 },
    { title: "Golden Time", score: 8 },
    { title: "Gravitation", score: 8 },
    { title: "Hajime no Ippo: Champion Road", score: 8 },
    { title: "Hajime no Ippo: Mashiba vs. Kimura", score: 8 },
    { title: "Hanma Baki: Son of Ogre", score: 8 },
    { title: "Hanma Baki: Son of Ogre 2nd Season", score: 8 },
    { title: "Hataraku Saibou", score: 8 },
    { title: "Hataraku Saibou Black", score: 8 },
    { title: "Hellsing", score: 8 },
    { title: "Hetalia Axis Powers", score: 8 },
    { title: "Ijiranaide, Nagatoro-san", score: 8 },
    { title: "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze", score: 8 },
    { title: "K-On!", score: 8 },
    { title: "Kimi ni Todoke 2nd Season: Minitodo Gekijou", score: 8 },
    { title: "Kogepan", score: 8 },
    { title: "Kono Subarashii Sekai ni Shukufuku wo!", score: 8 },
    { title: "Kono Subarashii Sekai ni Shukufuku wo! 2", score: 8 },
    { title: "Kono Subarashii Sekai ni Shukufuku wo! Movie: Kurenai Densetsu", score: 8 },
    { title: "Kono Subarashii Sekai ni Shukufuku wo!: Kono Subarashii Choker ni Shukufuku wo!", score: 8 },
    { title: "Kotarou wa Hitorigurashi", score: 8 },
    { title: "Kuroshitsuji", score: 8 },
    { title: "Mahouka Koukou no Rettousei", score: 8 },
    { title: "Medarot", score: 8 },
    { title: "Naruto: Shippuuden", score: 8 },
    { title: "Nijiiro Days", score: 8 },
    { title: "Noragami", score: 8 },
    { title: "Noragami Aragoto", score: 8 },
    { title: "Onegai☆Teacher", score: 8 },
    { title: "Onegai☆Teacher: Himitsu na Futari", score: 8 },
    { title: "Osomatsu-san", score: 8 },
    { title: "Ouran Koukou Host Club", score: 8 },
    { title: "Ousama Ranking", score: 8 },
    { title: "Psycho-Pass", score: 8 },
    { title: "Psycho-Pass 2", score: 8 },
    { title: "Psycho-Pass 3", score: 8 },
    { title: "Psycho-Pass Movie 1", score: 8 },
    { title: "ReLIFE", score: 8 },
    { title: "Rozen Maiden: Träumend", score: 8 },
    { title: "Sakamoto Days", score: 8 },
    { title: "Sekirei", score: 8 },
    { title: "Sekirei: Pure Engagement", score: 8 },
    { title: "Shingeki no Kyojin Season 2", score: 8 },
    { title: "Shingeki no Kyojin Season 3", score: 8 },
    { title: "Shingeki no Kyojin Season 3 Part 2", score: 8 },
    { title: "Shingeki no Kyojin: The Final Season", score: 8 },
    { title: "Shingeki no Kyojin: The Final Season Part 2", score: 8 },
    { title: "Shinseiki Evangelion", score: 8 },
    { title: "Soul Eater", score: 8 },
    { title: "Spy x Family", score: 8 },
    { title: "Subarashiki Kono Sekai The Animation", score: 8 },
    { title: "Suzumiya Haruhi no Shoushitsu", score: 8 },
    { title: "Tenjou Tenge", score: 8 },
    { title: "Tokyo Mew Mew", score: 8 },
    { title: "Tottoko Hamtarou", score: 8 },
    { title: "Trigun", score: 8 },
    { title: "Urusei Yatsura", score: 8 },
    { title: "Vampire Knight Guilty", score: 8 },
    { title: "Wotaku ni Koi wa Muzukashii", score: 8 },
    { title: "Yuyushiki", score: 8 },
    { title: "AIKa", score: 7 },
    { title: "Aa! Megami-sama! (TV)", score: 7 },
    { title: "Aggressive Retsuko (ONA)", score: 7 },
    { title: "Bakemono no Ko", score: 7 },
    { title: "Bakuten Shoot Beyblade", score: 7 },
    { title: "Black Cat", score: 7 },
    { title: "Bleach", score: 7 },
    { title: "Blood+", score: 7 },
    { title: "Bokusatsu Tenshi Dokuro-chan", score: 7 },
    { title: "Byousoku 5 Centimeter", score: 7 },
    { title: "D.N.Angel", score: 7 },
    { title: "Darker than Black: Ryuusei no Gemini", score: 7 },
    { title: "Demashita! Powerpuff Girls Z", score: 7 },
    { title: "Digimon Frontier", score: 7 },
    { title: "Fruits Basket", score: 7 },
    { title: "Futari wa Precure: Max Heart", score: 7 },
    { title: "Genshiken 2", score: 7 },
    { title: "Goblin Slayer", score: 7 },
    { title: "Hand Maid May", score: 7 },
    { title: "Hand Maid May: Akiramemasen", score: 7 },
    { title: "Hanma Baki vs. Kengan Ashura", score: 7 },
    { title: "Ichiban Ushiro no Daimaou", score: 7 },
    { title: "Ikkitousen", score: 7 },
    { title: "JoJo no Kimyou na Bouken (TV)", score: 7 },
    { title: "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders", score: 7 },
    { title: "Kaichou wa Maid-sama!", score: 7 },
    { title: "Kimetsu no Yaiba", score: 7 },
    { title: "Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo", score: 7 },
    { title: "Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo 2nd Season", score: 7 },
    { title: "Kimi no Na wa.", score: 7 },
    { title: "Koe no Katachi", score: 7 },
    { title: "Kyokou Suiri Season 2", score: 7 },
    { title: "Love Hina: Motoko no Sentaku, Koi ka Ken... \"Naku na\"", score: 7 },
    { title: "Love Live! School Idol Project", score: 7 },
    { title: "Mashle", score: 7 },
    { title: "Midori no Hibi", score: 7 },
    { title: "Mirai Nikki (TV)", score: 7 },
    { title: "Monster Farm: Legend e no Michi", score: 7 },
    { title: "Monster Musume no Iru Nichijou", score: 7 },
    { title: "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta...", score: 7 },
    { title: "ReLIFE: Kanketsu-hen", score: 7 },
    { title: "Sakamoto desu ga?", score: 7 },
    { title: "Serial Experiments Lain", score: 7 },
    { title: "Shingeki no Kyojin", score: 7 },
    { title: "Steins;Gate", score: 7 },
    { title: "Sword Art Online", score: 7 },
    { title: "To LOVE-Ru", score: 7 },
    { title: "Toradora!: Bentou no Gokui", score: 7 },
    { title: "Uchuu Patrol Luluco", score: 7 },
    { title: "Vampire Knight", score: 7 },
    { title: "Video Girl Ai", score: 7 },
    { title: "Witch Watch", score: 7 },
    { title: "Yu☆Gi☆Oh! Movie: Chou Yuugou! Toki wo Koeta Kizuna", score: 7 },
    { title: "Bishoujo Senshi Sailor Moon S", score: 6 },
    { title: "Boku dake ga Inai Machi", score: 6 },
    { title: "Chuunibyou demo Koi ga Shitai! Kirameki no... Slapstick Noel", score: 6 },
    { title: "Highschool of the Dead", score: 6 },
    { title: "Ichigo 100%", score: 6 },
    { title: "Junjou Romantica", score: 6 },
    { title: "Kyokou Suiri", score: 6 },
    { title: "Lalala Demacia", score: 6 },
    { title: "Nanatsu no Taizai", score: 6 },
    { title: "Nyan Koi!", score: 6 },
    { title: "One Punch Man", score: 6 },
    { title: "Ookami Shoujo to Kuro Ouji", score: 6 },
    { title: "Orange", score: 6 },
    { title: "Orange: Mirai", score: 6 },
    { title: "Sekaiichi Hatsukoi", score: 6 },
    { title: "Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san", score: 6 },
    { title: "Toradora!", score: 6 },
    { title: "Tsubasa Chronicle", score: 6 },
    { title: "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.", score: 5 },
    { title: "Beastars", score: 5 },
    { title: "Fairy Tail", score: 5 },
    { title: "JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai", score: 5 },
    { title: "Junjou Romantica 2", score: 5 },
    { title: "Sekaiichi Hatsukoi 2", score: 5 },
    { title: "Tonari no Kaibutsu-kun", score: 5 },
    { title: "Tonari no Kaibutsu-kun: Tonari no Gokudou-kun", score: 5 },
    { title: "Violet Evergarden", score: 5 },
    { title: "Wolverine", score: 5 },
    { title: "Yu☆Gi☆Oh! Zexal", score: 5 },
    { title: "Hyouka", score: 4 },
    { title: "Itazura na Kiss", score: 4 },
    { title: "Mitsu x Mitsu Drops", score: 4 },
    { title: "Suki tte Ii na yo.", score: 4 },
    { title: "Suki tte Ii na yo. Dareka ga", score: 4 },
    { title: "Suki tte Ii na yo.: Mei and Marshmallow", score: 4 },
    { title: "Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!", score: 4 },
    { title: "Another", score: 3 },
    { title: "Boku no Hero Academia", score: 3 },
    { title: "Boruto: Naruto the Movie", score: 3 },
    { title: "School Days", score: 3 },
    { title: "The Last: Naruto the Movie", score: 3 },
    { title: "Black★Rock Shooter (TV)", score: 2 },
    { title: "Inu x Boku SS", score: 2 },
    { title: "Kuzu no Honkai", score: 1 },
    { title: "Ore no Imouto ga Konnani Kawaii Wake ga Nai", score: 1 },
    { title: "Ore no Imouto ga Konnani Kawaii Wake ga Nai.", score: 1 },
    { title: "Ore no Imouto ga Konnani Kawaii Wake ga Nai. Specials", score: 1 },
  ],
};
